dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

addons:
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "cdadt"
    token:
      secure: 905f5eba405b0bafc9adf9f2026d30a3943f2052 # encrypted value of your token

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test-headless
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - sonar-scanner